version: '3'
services:
    react-app:
       image: sdey3141/react-app-new
       build:
        context: .
        dockerfile: Dockerfile.dev
       ports:
         - "3000:3000"
       volumes:
        - /home/node/app/node_modules
        - .:/home/node/app
    run-test:
        image: sdey3141/react-app-test
        build:
         context: .
         dockerfile: Dockerfile.dev
        volumes:
         - /home/node/app/node_modules
         - .:/home/node/app
        command: ["npm" , "run" , "test"]
